stages:
  - test

variables:
  CI_TEST_IMAGE: webdevops/php-nginx-dev:8.2
  COMPOSER_FLAGS: "--prefer-dist --no-progress --no-suggest --no-interaction"

test:
  stage: test
  image: $CI_TEST_IMAGE
  coverage: /^\s+Lines:\s+(\d+\.\d+%)/
  script:
    - composer install $COMPOSER_FLAGS
    - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text --display-warnings --do-not-cache-result --configuration=./phpunit.xml.dist
